[build]
  command = "yarn build:shared && yarn build:components && yarn doc:build"
  publish = "website/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["!node_modules/.cache/**/*", "!node_modules/@swc/**/*"]

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=8192"
