[build]
  command = "SKIP_BUILD_STATIC_GENERATION=&SKIP_BUILD_STATIC_GENERATION yarn doc:build"
  publish = "website/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=8192"

[context.deploy-preview.environment]
  SKIP_BUILD_STATIC_GENERATION = "true"