[build]
  command = "NODE_OPTIONS=$NODE_OPTIONS yarn doc:build"
  publish = "website/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=8192"
  NETLIFY_BUILD_DEBUG = "true"
