[build]
  command = "sed -i \"s|HEADER_PLACEHOLDER|${NEXT_PUBLIC_GA_ID}|g\" netlify.toml && yarn doc:build"
  publish = "website/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"



[build]



