[build]
  command = "yarn doc:build"
  publish = "website/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=8192"

[context.deploy-preview]
  command = 'echo $SKIP_BUILD_STATIC_GENERATION'
  environment = { SKIP_BUILD_STATIC_GENERATION = "true" }