name: Feature request 💡
description: Suggest an idea for this project
title: '[Feature Request]:'
labels:
  - feature request
body:
  - type: input
    id: component
    attributes:
      label: Component that this feature request involves
      description: Put the name of the component. If it's a request for a new component, put what you think it should be called.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: >-
        A clear and concise description of the problem. E.g. I'm always
        frustrated when [...]
  - type: textarea
    id: describe
    attributes:
      label: Describe the solution you'd like
      description: What would you like to see added to Igloo to solve the problem?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here. This includes any links to existing issues.
