const EditorTheme = {
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder: 'ids-rich-text-editor__placeholder',
  paragraph: 'ids-rich-text-editor__paragraph',
  quote: 'ids-rich-text-editor__quote',
  heading: {
    h1: 'ids-rich-text-editor__heading-h1',
    h2: 'ids-rich-text-editor__heading-h2',
    h3: 'ids-rich-text-editor__heading-h3',
    h4: 'ids-rich-text-editor__heading-h4',
    h5: 'ids-rich-text-editor__heading-h5',
  },
  list: {
    nested: {
      listitem: 'ids-rich-text-editor__nested-listitem',
    },
    ol: 'ids-rich-text-editor__list-ol',
    ul: 'ids-rich-text-editor__list-ul',
    listitem: 'ids-rich-text-editor__listitem',
  },
  image: 'ids-rich-text-editor__image',
  link: 'ids-rich-text-editor__link',
  text: {
    bold: 'ids-rich-text-editor__text-bold',
    italic: 'ids-rich-text-editor__text-italic',
    overflowed: 'ids-rich-text-editor__text-overflowed',
    hashtag: 'ids-rich-text-editor__text-hashtag',
    underline: 'ids-rich-text-editor__text-underline',
    strikethrough: 'ids-rich-text-editor__text-strikethrough',
    underlineStrikethrough: 'ids-rich-text-editor__text-underlineStrikethrough',
    code: 'ids-rich-text-editor__text-code',
  },
  code: 'ids-rich-text-editor__code',
  codeHighlight: {
    atrule: 'ids-rich-text-editor__tokenAttr',
    attr: 'ids-rich-text-editor__tokenAttr',
    boolean: 'ids-rich-text-editor__tokenProperty',
    builtin: 'ids-rich-text-editor__tokenSelector',
    cdata: 'ids-rich-text-editor__tokenComment',
    char: 'ids-rich-text-editor__tokenSelector',
    class: 'ids-rich-text-editor__tokenFunction',
    'class-name': 'ids-rich-text-editor__tokenFunction',
    comment: 'ids-rich-text-editor__tokenComment',
    constant: 'ids-rich-text-editor__tokenProperty',
    deleted: 'ids-rich-text-editor__tokenProperty',
    doctype: 'ids-rich-text-editor__tokenComment',
    entity: 'ids-rich-text-editor__tokenOperator',
    function: 'ids-rich-text-editor__tokenFunction',
    important: 'ids-rich-text-editor__tokenVariable',
    inserted: 'ids-rich-text-editor__tokenSelector',
    keyword: 'ids-rich-text-editor__tokenAttr',
    namespace: 'ids-rich-text-editor__tokenVariable',
    number: 'ids-rich-text-editor__tokenProperty',
    operator: 'ids-rich-text-editor__tokenOperator',
    prolog: 'ids-rich-text-editor__tokenComment',
    property: 'ids-rich-text-editor__tokenProperty',
    punctuation: 'ids-rich-text-editor__tokenPunctuation',
    regex: 'ids-rich-text-editor__tokenVariable',
    selector: 'ids-rich-text-editor__tokenSelector',
    string: 'ids-rich-text-editor__tokenSelector',
    symbol: 'ids-rich-text-editor__tokenProperty',
    tag: 'ids-rich-text-editor__tokenProperty',
    url: 'ids-rich-text-editor__tokenOperator',
    variable: 'ids-rich-text-editor__tokenVariable',
  },
};

export default EditorTheme;
