const EditorTheme = {
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder: 'ids-text-editor__placeholder',
  paragraph: 'ids-text-editor__paragraph',
  quote: 'ids-text-editor__quote',
  characterLimit: 'ids-text-editor__character-limit',
  heading: {
    h1: 'ids-text-editor__heading-h1',
    h2: 'ids-text-editor__heading-h2',
    h3: 'ids-text-editor__heading-h3',
    h4: 'ids-text-editor__heading-h4',
    h5: 'ids-text-editor__heading-h5',
  },
  list: {
    nested: {
      listitem: 'ids-text-editor__nested-list-item',
    },
    ol: 'ids-text-editor__list-ol',
    ul: 'ids-text-editor__list-ul',
    listitem: 'ids-text-editor__list-item',
  },
  image: 'ids-text-editor__image',
  link: 'ids-text-editor__link',
  text: {
    bold: 'ids-text-editor__text-bold',
    italic: 'ids-text-editor__text-italic',
    overflowed: 'ids-text-editor__text-overflowed',
    hashtag: 'ids-text-editor__text-hashtag',
    underline: 'ids-text-editor__text-underline',
    strikethrough: 'ids-text-editor__text-strikethrough',
    underlineStrikethrough: 'ids-text-editor__text-underlineStrikethrough',
    code: 'ids-text-editor__text-code',
  },
  code: 'ids-text-editor__code',
  codeHighlight: {
    atrule: 'ids-text-editor__token-attr',
    attr: 'ids-text-editor__token-attr',
    boolean: 'ids-text-editor__token-property',
    builtin: 'ids-text-editor__token-selector',
    cdata: 'ids-text-editor__token-comment',
    char: 'ids-text-editor__token-selector',
    class: 'ids-text-editor__token-function',
    'class-name': 'ids-text-editor__token-function',
    comment: 'ids-text-editor__token-comment',
    constant: 'ids-text-editor__token-property',
    deleted: 'ids-text-editor__token-property',
    doctype: 'ids-text-editor__token-comment',
    entity: 'ids-text-editor__token-operator',
    function: 'ids-text-editor__token-function',
    important: 'ids-text-editor__token-variable',
    inserted: 'ids-text-editor__token-selector',
    keyword: 'ids-text-editor__token-attr',
    namespace: 'ids-text-editor__token-variable',
    number: 'ids-text-editor__token-property',
    operator: 'ids-text-editor__token-operator',
    prolog: 'ids-text-editor__token-comment',
    property: 'ids-text-editor__token-property',
    punctuation: 'ids-text-editor__token-punctuation',
    regex: 'ids-text-editor__token-variable',
    selector: 'ids-text-editor__token-selector',
    string: 'ids-text-editor__token-selector',
    symbol: 'ids-text-editor__token-property',
    tag: 'ids-text-editor__token-property',
    url: 'ids-text-editor__token-operator',
    variable: 'ids-text-editor__token-variable',
  },
};

export default EditorTheme;
