name: CI - Canary

on:
  push:
    tags:
      - '*'
jobs:
  lint_and_test:
    if: ${{ startsWith(github.ref, 'refs/tags/@igloo-ui/**') }}
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        uses: actions/checkout@v2
