name: Publish Packages

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn lint:style

  test_and_build:
    name: Test and build
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test

  release:
    name: Release
    needs: [test_and_build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: yarn install --frozen-lockfile
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

  publish-npm:
    name: Publish to npm
    needs: [test_and_build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn publish-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
